import { Render } from '@puckeditor/core/rsc'
import { prisma } from '@/lib/db/prisma'
import { moduleEmbedOptions } from '@/lib/puck/module-embed-options'
import { moduleEmbedInjectors } from '@/lib/puck/module-embed-inject'
import type { LayoutRef } from '@/lib/puck/LayoutPickerField'

type LayoutEmbedProps = Record<string, unknown> & { layoutRef?: LayoutRef | null }

// Renders a saved Layout inline inside another page. The core block is
// module-agnostic: which options a layout exposes, and how those option values
// map onto the layout's blocks, both come from module-declared registries
// (generated by scripts/generate-module-layout-types.mjs). config.rsc is
// pulled in dynamically to avoid an import cycle (config.rsc wires this render
// into the LayoutEmbed component).
export async function LayoutEmbedRsc(props: LayoutEmbedProps) {
  const ref = props.layoutRef
  if (!ref?.id) return null

  const layout = await prisma.layout.findUnique({ where: { id: ref.id } }).catch(() => null)
  if (!layout?.builderData) return null

  const type = layout.type
  const options = moduleEmbedOptions[type] ?? []
  const values: Record<string, unknown> = {}
  for (const opt of options) {
    const raw = props[opt.key]
    values[opt.key] = raw !== undefined && raw !== '' ? raw : opt.default
  }

  const injector = moduleEmbedInjectors[type]
  const data = injector ? injector(layout.builderData, values) : layout.builderData

  const { getModuleLayoutPuckRscConfig } = await import('@/lib/puck/config.rsc')
  return <Render config={getModuleLayoutPuckRscConfig(type) as any} data={data as any} />
}
