// Shared font-picker option lists - used by the admin Styles page and the
// Puck SiteFontField. The full searchable catalogue lives in google-fonts.json;
// this is the no-search-term starter list plus the search-result cap.

export const MAX_FONT_SEARCH_RESULTS = 50

export const POPULAR_FONTS = [
  'system-ui, sans-serif',
  'Arial, sans-serif',
  'Georgia, serif',
  'Times New Roman, serif',
  'Helvetica, sans-serif',
  'Inter',
  'Roboto',
  'Open Sans',
  'Lato',
  'Poppins',
  'Montserrat',
  'Raleway',
  'Oswald',
  'Nunito',
  'Ubuntu',
  'Playfair Display',
  'Merriweather',
  'Source Sans Pro',
  'Source Serif Pro',
  'PT Sans',
  'PT Serif',
  'Noto Sans',
  'Noto Serif',
  'Libre Baskerville',
  'Libre Franklin',
  'Work Sans',
  'DM Sans',
  'DM Serif Display',
  'Outfit',
  'Figtree',
  'Plus Jakarta Sans',
  'Sora',
  'Space Grotesk',
  'Manrope',
  'Barlow',
  'Josefin Sans',
  'Cormorant Garamond',
  'EB Garamond',
  'Crimson Text',
  'Lora',
  'Bitter',
  'Spectral',
  'Mulish',
  'Quicksand',
  'Cabin',
  'Karla',
  'Rubik',
  'Jost',
  'Lexend',
  'IBM Plex Sans',
  'IBM Plex Serif',
  'Fira Sans',
  'Inconsolata',
]
