export type CustomThirdParty = { label: string; description: string }

export type WizardAnswers = {
  siteName: string
  websiteUrl: string
  contactEmail: string
  businessAddress: string
  dataCollected: string[]
  purposes: string[]
  thirdParties: string[]
  customThirdParties: CustomThirdParty[]
  jurisdiction: 'eu-uk' | 'us' | 'both' | 'unsure'
  cookies: boolean
  minimumAge: 'none' | 'under-13' | 'under-16'
  dpoName: string
  dpoEmail: string
}

export const DATA_COLLECTED_OPTIONS = [
  { key: 'names', label: 'Names' },
  { key: 'emails', label: 'Email addresses' },
  { key: 'ip', label: 'IP addresses' },
  { key: 'analytics', label: 'Analytics and usage data' },
  { key: 'payment', label: 'Payment information' },
  { key: 'location', label: 'Location data (derived from IP)' },
  { key: 'device', label: 'Device and browser information' },
  { key: 'content', label: 'Content you submit (messages, comments, forms)' },
]

export const PURPOSE_OPTIONS = [
  { key: 'service', label: 'Providing and operating our services' },
  { key: 'account', label: 'Managing your account' },
  { key: 'marketing', label: 'Sending marketing communications (with your consent)' },
  { key: 'analytics', label: 'Understanding how visitors use the site' },
  { key: 'legal', label: 'Complying with legal obligations' },
  { key: 'security', label: 'Detecting and preventing fraud or security threats' },
]

export const DISCLAIMER_TEXT =
  'Legal disclaimer: This privacy policy was generated by the Cactus privacy policy wizard. ' +
  'It is a starting point only and does not constitute legal advice. You should review this document carefully ' +
  '- and ideally with a qualified legal professional - before publishing it. Data protection laws vary by ' +
  'jurisdiction and change over time. The authors of this generator accept no liability for the accuracy, ' +
  'completeness, or fitness for purpose of the text below.'

export const DISCLAIMER = `> **${DISCLAIMER_TEXT}**`

function formatHost(url: string): string {
  if (!url) return ''
  try {
    const u = new URL(url.startsWith('http') ? url : `https://${url}`)
    return u.hostname
  } catch {
    return url
  }
}

function today(): string {
  return new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
}

function jurisdictionIncludesEu(answers: WizardAnswers): boolean {
  return answers.jurisdiction === 'eu-uk' || answers.jurisdiction === 'both'
}

function jurisdictionIncludesUs(answers: WizardAnswers): boolean {
  return answers.jurisdiction === 'us' || answers.jurisdiction === 'both'
}

function intro(answers: WizardAnswers): string {
  const host = formatHost(answers.websiteUrl)
  const siteRef = host ? `${answers.siteName || 'This website'} (${host})` : (answers.siteName || 'This website')
  const email = answers.contactEmail || '[contact email]'
  return `# Privacy Policy

*Last updated: ${today()}*

This privacy policy explains how ${siteRef} collects, uses, and protects your personal information when you visit or use our website.

We take your privacy seriously. Please read this policy carefully. If you have any questions, contact us at ${email}.`
}

function whatWeCollect(keys: string[]): string {
  if (!keys.length) {
    return `## What information we collect

We collect only the information necessary to operate our services. We do not sell your personal data.`
  }

  const labels: Record<string, string> = {
    names: 'Your name',
    emails: 'Your email address',
    ip: 'Your IP address (used for security and abuse prevention)',
    analytics: 'Analytics and usage data (pages visited, time on site, device type)',
    payment: 'Payment information (processed securely via our payment provider - we do not store card details ourselves)',
    location: 'Approximate location derived from your IP address',
    device: 'Device and browser information (type, operating system, browser version)',
    content: 'Content you submit, such as messages, comments, or form responses',
  }

  const items = keys.map((k) => `- ${labels[k] ?? k}`).join('\n')
  return `## What information we collect

We may collect the following types of personal information:

${items}

We collect this information only when you provide it directly, when you use our site, or where we are permitted to do so by law.`
}

function whyWeCollect(keys: string[]): string {
  if (!keys.length) {
    return `## How we use your information

We use the information we collect solely to operate and improve our website and services.`
  }

  const labels: Record<string, string> = {
    service: 'Provide, operate, and maintain our website and services',
    account: 'Create and manage your account',
    marketing: 'Send you marketing communications where you have given your consent (you can opt out at any time)',
    analytics: 'Understand how visitors use our site so we can improve it',
    legal: 'Comply with our legal obligations',
    security: 'Detect, prevent, and address fraud, security issues, and abuse',
  }

  const items = keys.map((k) => `- ${labels[k] ?? k}`).join('\n')
  return `## How we use your information

We use the information we collect to:

${items}`
}

function thirdPartiesBlock(categories: string[], custom: CustomThirdParty[]): string {
  const descriptions: Record<string, string> = {
    analytics: 'We use analytics services to understand how visitors use our site - for example, which pages are most popular and how users navigate. These services may set cookies and collect data about your browser and activity.',
    marketing: 'We use marketing and advertising services that may collect data about your visit in order to show you relevant adverts elsewhere on the internet.',
    preferences: 'We use services that remember your preferences and settings across visits, such as your chosen language or display options.',
  }

  const knownParas = categories.map((k) => descriptions[k] ?? `We use ${k} services on our site.`)
  const customParas = custom.map(({ label, description }) =>
    description.trim() || `We use ${label.toLowerCase()} services on our site.`
  )
  const allParas = [...knownParas, ...customParas].join('\n\n')

  return `## Third-party services

We share data with trusted third parties only where necessary to operate our services. We do not sell your personal data to third parties.

${allParas}

These third-party services have their own privacy policies and we encourage you to review them.`
}

function cookiesClause(): string {
  return `## Cookies

Our website uses cookies - small text files placed on your device. We use cookies to:

- Keep you signed in between visits
- Remember your preferences
- Understand how you use the site (analytics)

You can manage your cookie preferences at any time using our cookie preferences panel. Most browsers also allow you to control cookies through their settings. Refusing certain cookies may affect how the site functions.`
}

function gdprRights(answers: WizardAnswers): string {
  const email = answers.contactEmail || '[contact email]'
  return `## Your rights (GDPR and UK GDPR)

Under the General Data Protection Regulation (GDPR) and, where applicable, the UK GDPR, you have the following rights regarding your personal data:

- **Right to access** - you may request a copy of the personal data we hold about you.
- **Right to rectification** - you may ask us to correct inaccurate or incomplete data.
- **Right to erasure** - you may request that we delete your data in certain circumstances.
- **Right to restrict processing** - you may ask us to pause how we use your data.
- **Right to data portability** - you may request your data in a structured, machine-readable format.
- **Right to object** - you may object to processing based on legitimate interests, including direct marketing.
- **Right to withdraw consent** - where processing relies on your consent, you may withdraw it at any time.

To exercise any of these rights, please contact us at ${email}. We will respond within one month. You also have the right to lodge a complaint with a supervisory authority - in the UK, the Information Commissioner's Office (ico.org.uk); in the EU, your national data protection authority.`
}

function ccpaRights(answers: WizardAnswers): string {
  const email = answers.contactEmail || '[contact email]'
  return `## Your rights (California)

If you are a resident of California, the California Consumer Privacy Act (CCPA) and California Privacy Rights Act (CPRA) give you the following rights:

- **Right to know** - you may request details of the personal information we collect, use, disclose, and sell.
- **Right to delete** - you may request deletion of personal information we have collected about you.
- **Right to correct** - you may request correction of inaccurate personal information.
- **Right to opt out of sale or sharing** - we do not sell or share your personal information.
- **Right to non-discrimination** - we will not treat you less favourably for exercising your privacy rights.

To exercise your rights, please contact us at ${email}.`
}

function childrensClause(answers: WizardAnswers): string {
  const age = answers.minimumAge === 'under-13' ? 13 : 16
  const email = answers.contactEmail || '[contact email]'
  return `## Children's privacy

Our website is not directed at children under the age of ${age}. We do not knowingly collect personal information from children under ${age}. If you are a parent or guardian and believe we have collected information about your child, please contact us at ${email} and we will delete it promptly.`
}

function dpoClause(answers: WizardAnswers): string {
  const contact = answers.dpoEmail ? `${answers.dpoName}  \n${answers.dpoEmail}` : answers.dpoName
  return `## Data protection officer

Our Data Protection Officer is responsible for overseeing questions relating to this privacy policy:

**${contact}**`
}

function contactBlock(answers: WizardAnswers): string {
  const parts = [`**${answers.siteName || 'The site operator'}**`]
  if (answers.businessAddress) parts.push(answers.businessAddress)
  if (answers.contactEmail) parts.push(answers.contactEmail)
  return `## Contact us

If you have any questions, concerns, or requests about this privacy policy or how we handle your data, please get in touch:

${parts.join('  \n')}`
}

function lastUpdated(): string {
  return `*This policy was generated on ${today()} and should be reviewed regularly to ensure it remains accurate and up to date.*`
}

export function assemblePolicyMarkdown(answers: WizardAnswers): string {
  const blocks: string[] = []
  blocks.push(DISCLAIMER)
  blocks.push(intro(answers))
  blocks.push(whatWeCollect(answers.dataCollected))
  blocks.push(whyWeCollect(answers.purposes))
  if (answers.thirdParties.length || answers.customThirdParties.length) blocks.push(thirdPartiesBlock(answers.thirdParties, answers.customThirdParties))
  if (answers.cookies) blocks.push(cookiesClause())
  if (jurisdictionIncludesEu(answers)) blocks.push(gdprRights(answers))
  if (jurisdictionIncludesUs(answers)) blocks.push(ccpaRights(answers))
  if (answers.minimumAge !== 'none') blocks.push(childrensClause(answers))
  if (answers.dpoName) blocks.push(dpoClause(answers))
  blocks.push(contactBlock(answers))
  blocks.push(lastUpdated())
  return blocks.join('\n\n')
}
