import type { PrismaClient } from '@prisma/client'

// ---------------------------------------------------------------------------
// Styles info page — a living reference that renders real examples of every
// option on Admin > Appearance > Styles, so authors can see their theme choices
// applied to headings, body text, links, colours, buttons, images and form
// fields on a single public page.
//
// Rendered as a builder page containing one RichTextBlock of raw HTML. The
// public/RSC render path pipes that string straight to the DOM, so the elements
// pick up the theme's `main h1 … main input` rules generated by buildTokenStyles.
// A small scoped <style> neutralises the .puck-richtext overrides for heading
// size/colour and link colour so those tabs demo faithfully.
// ---------------------------------------------------------------------------

export const STYLES_PAGE_SLUG = 'style-guide'
export const STYLES_PAGE_TITLE = 'Styles'

const swatch = (label: string, cssVar: string) =>
  `<div style="display:flex;flex-direction:column;gap:.4rem;align-items:center">
     <div style="width:100%;height:56px;border-radius:6px;background:${cssVar};border:1px solid var(--color-border)"></div>
     <span style="font-size:.8125rem;color:var(--color-muted)">${label}</span>
   </div>`

const styleGuideHtml = `
<style>
  .sg{max-width:960px;margin:0 auto}
  .sg h1{font-size:var(--h1-size,2.5rem);color:var(--h1-color,var(--color-fg))}
  .sg h2{font-size:var(--h2-size,1.875rem);color:var(--h2-color,var(--color-fg))}
  .sg h3{font-size:var(--h3-size,1.5rem);color:var(--h3-color,var(--color-fg))}
  .sg h4{font-size:var(--h4-size,1.25rem);color:var(--h4-color,var(--color-fg))}
  .sg h5{font-size:var(--h5-size,1.125rem);color:var(--h5-color,var(--color-fg))}
  .sg h6{font-size:var(--h6-size,1rem);color:var(--h6-color,var(--color-fg))}
  .sg p{color:inherit;line-height:inherit}
  .sg a{color:var(--color-link,var(--color-primary))}
  .sg a:hover{color:var(--color-link-hover,var(--color-primary))}
  .sg img{max-width:100%;height:auto}
  .sg-label{display:block;font-size:.75rem;font-weight:600;letter-spacing:.08em;text-transform:uppercase;color:var(--color-muted);margin:0 0 .5rem}
  .sg-card{border:1px solid var(--color-border);border-radius:10px;padding:1.5rem;margin:0 0 1.5rem;background:var(--color-bg-subtle)}
  .sg-swatches{display:grid;grid-template-columns:repeat(auto-fill,minmax(96px,1fr));gap:1rem;margin:1rem 0 0}
  .sg-row{display:flex;flex-wrap:wrap;gap:.75rem;align-items:center}
  .sg-field{display:flex;flex-direction:column;gap:.35rem;margin:0 0 1rem;max-width:420px}
  .sg-hint{font-size:.8125rem;color:var(--color-muted);margin:.35rem 0 0}
</style>
<div class="sg">
  <p><strong>This is your style guide.</strong> Every heading, colour, button and field below is drawn live from
  <em>Appearance &rarr; Styles</em>. Change a setting there, revisit this page, and you will see it here.
  Handy for checking things actually look the way you intended before anyone else does.</p>
  <hr />

  <span class="sg-label">Colours</span>
  <h2>Colour palette</h2>
  <p>Your named colours become the palette used throughout Layouts. The primary colour also drives buttons,
  links and accents across the site.</p>
  <div class="sg-swatches">
    ${swatch('Primary', 'var(--color-primary)')}
    ${swatch('Colour 1', 'var(--color-1)')}
    ${swatch('Colour 2', 'var(--color-2)')}
    ${swatch('Link', 'var(--color-link, var(--color-primary))')}
    ${swatch('Text', 'var(--color-fg)')}
    ${swatch('Muted', 'var(--color-muted)')}
    ${swatch('Border', 'var(--color-border)')}
  </div>
  <hr />

  <span class="sg-label">Fonts &amp; Typography</span>
  <h2>Body text</h2>
  <p>This paragraph uses your body font, size and line height. Prose should be comfortable to read without
  anyone squinting: not too cramped, not so airy it drifts apart. Here is some <strong>bold text</strong>,
  some <em>italic text</em>, and a <a href="#body">themed link</a> so you can see the link colour in context
  (hover over it for the hover colour).</p>
  <ul>
    <li>Unordered lists inherit the body styles.</li>
    <li>Useful for a quick, unranked rattle through things.</li>
    <li>Each item sits on the same typographic footing.</li>
  </ul>
  <ol>
    <li>Ordered lists, for when sequence matters.</li>
    <li>Second in the queue.</li>
    <li>And a third, bringing up the rear.</li>
  </ol>
  <blockquote>A blockquote, for when you want to borrow someone else's words and look thoughtful doing it.</blockquote>
  <hr />

  <span class="sg-label">Headings</span>
  <h2>Heading scale</h2>
  <p>All six heading levels, each reflecting the size, colour and font you set on the Headings tab.</p>
  <h1>Heading level 1</h1>
  <h2>Heading level 2</h2>
  <h3>Heading level 3</h3>
  <h4>Heading level 4</h4>
  <h5>Heading level 5</h5>
  <h6>Heading level 6</h6>
  <hr />

  <span class="sg-label">Buttons</span>
  <h2>Buttons</h2>
  <p>These are real buttons and reflect the text, background, border and hover styles from the Buttons tab.
  Hover over them to see the hover state.</p>
  <div class="sg-row">
    <button type="button">Primary action</button>
    <button type="button">Another button</button>
  </div>
  <p class="sg-hint">Left unstyled on the Buttons tab, these fall back to the browser default. Set colours and
  radius there to bring them to life.</p>
  <hr />

  <span class="sg-label">Images</span>
  <h2>Images</h2>
  <p>Images pick up the border radius, width and colour from the Images tab.</p>
  <div class="sg-card" style="padding:0;overflow:hidden;background:none">
    <img src="https://picsum.photos/seed/cactus-style-guide/960/420" alt="A placeholder image demonstrating the configured image styles" />
  </div>
  <hr />

  <span class="sg-label">Form Fields</span>
  <h2>Form fields</h2>
  <p>Labels and fields use the typography, colours and border styles from the Form Fields tab. The same styles
  apply to any forms rendered on your public pages.</p>
  <div class="sg-field">
    <label for="sg-name">Your name</label>
    <input id="sg-name" type="text" placeholder="Ada Lovelace" />
  </div>
  <div class="sg-field">
    <label for="sg-email">Email address</label>
    <input id="sg-email" type="email" placeholder="ada@example.com" />
  </div>
  <div class="sg-field">
    <label for="sg-topic">Topic</label>
    <select id="sg-topic">
      <option>General enquiry</option>
      <option>Something is on fire</option>
      <option>Just saying hello</option>
    </select>
  </div>
  <div class="sg-field">
    <label for="sg-message">Message</label>
    <textarea id="sg-message" rows="4" placeholder="Say something nice…"></textarea>
  </div>
</div>
`.trim()

export const stylesInfoPageData = {
  root: { props: {} },
  content: [
    {
      type: 'Section',
      props: {
        id: 'style-guide-section',
        bg: { mode: 'none', color: '' }, bgImage: '', bgSize: 'cover',
        overlayColor: '', overlayOpacity: 0, paddingY: 'lg', maxWidth: 'standard',
        textColor: '', sticky: 'off', stickyOffset: '0px', boxShadow: 'none',
        borderStyle: 'none', borderColor: 'var(--color-border)', borderWidth: '1px',
        borderRadius: 'none', opacity: '100',
        animationType: 'none', animationDuration: 'normal', animationDelay: 'none',
        content: [
          { type: 'RichTextBlock', props: { id: 'style-guide-richtext', content: styleGuideHtml, padding: 'none' } },
        ],
      },
    },
  ],
  zones: {},
}

// Upserts the Styles info page as an installed-by-default draft. Idempotent:
// safe to run on every setup/reset. Only ever writes builderData (the working
// draft) so a published copy is never created until an admin publishes it.
export async function upsertStylesInfoPage(db: PrismaClient) {
  await db.infoPage.upsert({
    where: { slug: STYLES_PAGE_SLUG },
    create: {
      slug: STYLES_PAGE_SLUG,
      title: STYLES_PAGE_TITLE,
      body: '',
      bodyFormat: 'builder',
      builderData: stylesInfoPageData,
      status: 'draft',
      metaDescription: 'A live reference showing every option from Appearance > Styles applied on one page.',
    },
    update: {
      bodyFormat: 'builder',
      builderData: stylesInfoPageData,
    },
  })
}
